version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: my-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: appdb

volumes:
  mongo-data:
